apiVersion: v2
name: helm-onix
description: A Helm chart for Please Protect Center

type: application
version: 1.0.0
appVersion: "1.0"

dependencies:

  ### pgSQL ###
  ### ไม่ใช้แล้วแต่ว่าให้คงไว้ก่อน
  - name: "postgresql"
    alias: postgresql-onix
    condition: postgresql-onix.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "16.7.15"

  ### PostgreSQL V2 ###
  - name: "postgresql-v2"
    alias: postgresql-v2
    condition: postgresql-v2.enabled
    version: "1.0.0"

  ### Redis ###
  - name: "redis"
    alias: redis
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.13.0"

  ### Onix API ###
  - name: "generic-app"
    alias: onix-api
    condition: onix-api.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### Please Protect Center ###
  - name: "generic-app"
    alias: please-protect-center
    condition: please-protect-center.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
