apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-sa-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: gcp-sa-secret    # name of the k8s Secret to be created
  data:
  - secretKey: sa.json
    remoteRef:
      key: onix-v2-gcp-sa
      version: latest
