---
envAlias: development
envAliasJob: Development
envGroup: dev

domainOnixPpAPI: api-dev.pp-center.local
pleaseProtectCenterDomain: center-dev.pp-center.local

pgDiskSize: 30Gi
pgHost: postgresql-onix
