apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: idp-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: idp-secret      # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
{{- if .Values.envAlias eq "development" }}
  - secretKey: IDP_CLIENT_ID
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_CLIENT_ID_DEV

  - secretKey: IDP_CLIENT_SECRET
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_CLIENT_SECRET_DEV

  - secretKey: IDP_URL_PREFIX
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_URL_PREFIX_DEV

  - secretKey: IDP_REALM
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_REALM_DEV
{{ else }}
  - secretKey: IDP_CLIENT_ID
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_CLIENT_ID_PROD

  - secretKey: IDP_CLIENT_SECRET
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_CLIENT_SECRET_PROD

  - secretKey: IDP_URL_PREFIX
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_URL_PREFIX_PROD

  - secretKey: IDP_REALM
    remoteRef:
      key: "initial-secret-preset"
      property: IDP_REALM_PROD
{{ end }}
