onix-api:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: '/secrets/sa.json'

      #- name: STORAGE_BUCKET
      #  value: 'onix-v2-artifacts'

      - name: ENV_GROUP
        value: 'dev'

      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Development"

      - name: LOG_ENDPOINT
        value: "http://logstash-http.logstash-etl.svc.cluster.local:8080"

      - name: IsDev
        value: "true"

      #- name: ScanItem__RedirectUrl
      #  value: "https://verify-dev.please-scan.com/verify"

      #- name: ScanItem__SymmetricKey
      #  valueFrom:
      #    secretKeyRef:
      #      name: scan-item-secret
      #      key: ENCRYPTION_KEY
      #      optional: false

      #- name: ScanItem__EncryptionIv
      #  valueFrom:
      #    secretKeyRef:
      #      name: scan-item-secret
      #      key: ENCRYPTION_IV
      #      optional: false

      - name: PostgreSQL__Host
        value: "postgresql-onix"

      - name: PostgreSQL__Database
        value: "onix"

      - name: PostgreSQL__User
        value: "postgres"

      - name: PostgreSQL__Password
        valueFrom:
          secretKeyRef:
            name: onix-postgres-secret
            key: adminPasswordKey
            optional: false

      - name: Redis__Host
        value: "redis-master"

      - name: Redis__Port
        value: "6379"

      - name: IDP_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_ID
            optional: false

      - name: IDP_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_CLIENT_SECRET
            optional: false

      - name: IDP_URL_PREFIX
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_URL_PREFIX
            optional: false

      - name: IDP_REALM
        valueFrom:
          secretKeyRef:
            name: idp-secret
            key: IDP_REALM
            optional: false
